<?php include 'view/inc/header.inc.php';
require 'model/database_mysqli.php';
?>
<br>
<?php global $msg; ?>
<!-- display login info -->
<div class="container">Welcome <?php echo $_SESSION["username"]?>
<form method="POST" class="inline-form">
     <input type="hidden" name="action" value="logout">
     <button type='submit' name='logout'>Logout</button>
</form>
</div>

<div class="container">
    <!-- nav menu -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
                <div class="navbar-nav">
                    <a class="nav-link active" aria-current="page" href="?page=clients">Clients</a> 
                    <a class="nav-link" href="?page=notifications">Notifications</a>
                    <a class="nav-link" href="?page=employees">Employees</a>
                    <a class="nav-link" href="?page=logs">Activity Log</a>
                    <a class="nav-link" href="?page=about_us">About Us</a>
                </div>
            </div>
        </div>
    </nav>

    <br>
    <a class="btn btn-sm btn-primary" href="?page=client_create" role="button"><i class="fa fa-plus"></i> Add New Client</a>
    <br>

    <?php global $db_con;?>
    <!-- displaying data for each item -->
    <table class="table table-responsive table-wrapper">
        <thead>
            <tr>
                <th scope="col">Client ID</th>
                <th scope="col">Company Name</th>
                <th scope="col">Business Number</th>
                <th scope="col">First Name</th>
                <th scope="col">Last Name</th>
                <th scope="col">Phone Number</th>
                <th scope="col">Cell Number</th>
                <th scope="col">Carrier</th>
                <th scope="col">HST Number</th>
                <th scope="col">Website</th>
                <th scope="col">Status</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($clients as $client) : ?>
                <tr>
                    <td><?= $client['client_id'] ?></td>
                    <td><?= $client['company_name'] ?></td>
                    <td><?= $client['business_number'] ?></td>
                    <td><?= $client['client_first_name'] ?></td>
                    <td><?= $client['client_last_name'] ?></td>
                    <td><?= $client['client_phone_number'] ?></td>
                    <td><?= $client['client_cell_number'] ?></td>
                    <td><?= $client['carrier'] ?></td>
                    <td><?= $client['hst_number'] ?></td>
                    <td><?= $client['website'] ?></td>
                    <td><?= $client['client_status'] ?></td>
                    <td>
                        <a class="btn btn-sm btn-primary" href="?page=client_update&id=<?= $client['client_id'] ?>" role="button">Update</a>
                        <!-- update status -->
                        <?php include 'view/status_change.phtml' ?>
                    </td>

                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
<!-- include the events page inside the clients to show event status impacted by client status change -->
    <?php include 'view/events.phtml';?>
    <footer>&copy; Copyright 2021 - </footer>
        <script src=https://my.gblearn.com/js/loadscript.js></script>
    </div>

    <div>
        <?php 
        echo "<hr>";
        show_source(__FILE__);
        ?>
    </div>
</body>
</html>