<!-- employee update status form -->
<form method="post" class="inline-form">
    <input type="hidden" name="id" value="<?=$employee["employee_id"]?>">
    <input type="hidden" name="status" value="<?=$employee["employee_status"]?>">
    <button type="submit" name="action" value="employee_status" class="btn btn-sm btn-danger" onClick="javascript: return confirm('Do you want to change the status of this employee?');">
        Change Status
    </button>
</form>