<!-- event update status form -->
<form method="post" class="inline-form">
    <input type="hidden" name="id" value="<?=$event["event_id"]?>">
    <input type="hidden" name="status" value="<?=$event["event_status"]?>">
    <button type="submit" name="action" value="event_status" class="btn btn-sm btn-danger" onClick="javascript: return confirm('Do you want to change the status of this event?');">
        Change Status
    </button>
</form>